sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-063.pdf --upload --lsstdoc DMTN-063.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="dmtn-063"
    - secure: "N/4DT35El9hh2iBg370ESFqjzSuMxr/ba75J/OwEncPWK1YJbnZIaie+30fiR1E0Yup6b+QqhzlVcukW0yqjKqHF9We4hG33H04OcWfiRxpjBnwX6O2LbrkuheIodYPqfsl7yGJJV3okPBox6+9yKsYkNHuUIn92VpOCO2Mo3HsPeg7yWotvEGPlO3pVedlpp4A+poolLBtUU97w5gVPl35Pa9pBWAW1PwzFl2EmBofUsPhmU9V9Wk8cJ7ZrgEPdQWsT40WlzNzQH+r2fwyBM4rKlz3E0pyeLFQ+GhoAcDPKWKU+Yrloh/z9TiS/NNYBfyVaNb9TZkOwpc1s7NBr/grLnsol7jbRghfJWt6XMxHjXsSNLAiNJDOcNthL7Y8qCJ1g5Z1qqlr0VlhRn2ooTzO16B8T0aas/fttZp2Gs5BM9X6soKdbHoiz1DvbtMAcX5UABh8hmbNypA78DmT0qCGXSe8DmHLb9K9ClfHedLVwiXHS3FOacD9kx1+UekC4ZeeZ/Q9xX5MPWoYIQ8RIQgAU1TwW/yE7MXUSY2s0fDgbDVnQWhCGQ/6SxoeBiyyGWtv0ByLphcrQiWDdo1o/4EabSGQUXfjjW4cFeDIyngDMVW2oj/Iffsgx0LOoulcC3lh23CBbODgPT9B/ZeN1eKE+hqVREajkDX4IfnUYY0w="
    - secure: "Dbtc7ts7yLBPx2GN9hT/eSz40D4sg7cwax6KWOt/CC8DnE2obbtdD/6KZ+WTS8+ZTL1SqkwtZIq8bvl18L3Yb0xAR1jGPdkYNL/TPYHyjlA7D+YJmgQpv8yft/bkuv5O6/n0bFXjDQdoNvfYhRNdLjMZroBeOlHA9Enq285BQXKeQhZhEvhGogyE24GBQHrVCiQcgsGdTdNU2FzfuWMBuODsoNVB2tvzwstEbBVY/rdhcbgAO4lEsZUiEkTeSjQN+BBsDs4QzwIiu1F59wpG8bQursAmw1osnE01aBF104q+iy41OLtbwZCLo8vWyxkGeh6F1q4AuYo+5M7gzgjx97QT2CorBur+YsYzGfqNteGuX7KWOEix+XiPhV8K4k3ky6kcdLj3XDzQwGhgsBV2Tu4qNvCK9Mj+BFuK5bTOW7dOyp5je3Qnw9Xoqpw1+MP/wPruGLwURYg9KO1OOzmVAFzuF/Lfglx8PdDQF7N5eg0AXipItlqs01FTlWJggGLX61KUvOXzWPgTYXR0/4ActFnzK/JKFXYLE4JERUh1UNTG2K9vixFjVqaYLv4PqK04xxJKxOsSxaY6dCbfXwsacPsvpXFqUnyYDCDV+HdwWkk5ERmJx0TBR4QupaB4nYROKYrX0nJOcp36aiFXcVbyxhe2oixznND5LYUhPasimqw="
